spring.application.name=url-shortener-sb
spring.datasource.url = jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username = root
spring.datasource.password = password
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
jwt.secret = Y2hvb25nZWV0aGVpZ2h0aWVzYW5kZmlmdHlzaXhiaXRzZXNzdXBlcnNlY3VyZQ==
jwt.expiration = 172800000